services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env.dev
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data_dev:/data/db
    env_file:
      - .env.dev
    command: mongod -port 27018 --auth

volumes:
  mongodb_data_dev: