services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env.prod

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_prod:/data/db
    env_file:
      - .env.prod
    command: mongod --auth

volumes:
  mongodb_data_prod: